dist: bionic
os: linux
language: clojure
cache:
  directories:
    - "$HOME/.m2"
before_install:
  - npm i -g npm
  - yes y | sudo lein upgrade
  - curl -sSL https://raw.githubusercontent.com/cljs-oss/canary/master/scripts/install-canary.sh | bash
script:
  - lein karma-once
