version: 2.1
orbs:
  cljs:
    executors:
      lein_browsers:
        docker:
          - image: circleci/clojure:openjdk-11-lein-2.9.1-node-browsers
        working_directory: ~/repo
        environment:
          LEIN_ROOT: "true"
          # Customize the JVM maximum heap limit
          JVM_OPTS: -Xmx3200m
    commands:
      test-cljs:
        description: "Build and test CLJS projects"
        steps:
          - checkout

          # Download and cache dependencies
          - restore_cache:
              keys:
                - v1-dependencies-{{ checksum "project.clj" }}
                # fallback to using the latest cache if no exact match is found
                - v1-dependencies-

          - run:
              command: sudo npm install -g karma-cli

          # run tests.
          - run:
              command: lein karma-once

          - run:
              command: karma start --single-run --reporters junit,dots

          - save_cache:
              paths:
                - ~/.m2
                - node_modules
                - .shadow-cljs
              key: v1-dependencies-{{ checksum "project.clj" }}

jobs:
  build:
    executor: cljs/lein_browsers
    steps:
      - cljs/test-cljs
