name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: [bug, triage]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of re-frame are you using?
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers or runtimes are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Microsoft Edge
        - Node.js
        - JVM (CLJC)
        - Other (please specify)
  - type: textarea
    id: logs
    attributes:
      label: Relevant console output
      description: Please copy and paste any relevant console output. This will be automatically formatted into code, so no need for backticks.
      render: shell
