blank_issues_enabled: false
contact_links:
  - name: re-frame GitHub Discussions
    url: https://github.com/day8/re-frame/discussions
    about: Ask and answer questions in GitHub Flavored Markdown.
  - name: "#re-frame Clojurians Slack Chat"
    url: https://clojurians.slack.com
    about: Active channel for real-time discussion, questions and answers. Clojurians is a Slack Pro account Sponsored by Slack Technologies, LLC.
  - name: "Stack Overflow Questions tagged [re-frame]"
    url: https://stackoverflow.com/questions/tagged/re-frame
    about: Stack Overflow
