blank_issues_enabled: false
contact_links:
  - name: re-frame Community Support
    url: https://github.com/day8/re-frame/discussions
    about: Please ask and answer questions here.
  - name: "#re-frame Clojurians Slack Chat"
    url: https://clojurians.slack.com
    about: Loses history, but is very active.
