name: ci
on:
  push:
    paths-ignore:
      - "bin/**"
      - "docs/**"
      - "images/**"
      - ".editorconfig"
      - ".gitignore"
      - "CHANGELOG.md"
      - "CITATION.md"
      - "CONTRIBUTING.md"
      - "license.txt"
      - "README.md"

jobs:
  test:
    name: Test
    runs-on: ubuntu-18.04
    container:
      # Source: https://github.com/day8/dockerfile-for-dev-ci-image
      image: docker.pkg.github.com/day8/dockerfile-for-dev-ci-image/dev-ci:0.1
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Maven cache
        id: maven-cache
        uses: actions/cache@v2
        with:
          path: /root/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/project.clj', '.github/workflows/**') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: npm cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('project.clj') }}-${{ hashFiles('**/deps.cljs') }}
          restore-keys: |
            ${{ runner.os }}-npm-
      - name: shadow-cljs compiler cache
        uses: actions/cache@v2
        with:
          path: .shadow-cljs
          key: ${{ runner.os }}-shadow-cljs-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-shadow-cljs-
      - if: steps.maven-cache.outputs.cache-hit != 'true'
        run: lein ci
      - if: steps.maven-cache.outputs.cache-hit != 'true'
        name: Run cd examples/simple && lein shadow-release && lein build-report
        working-directory: examples/simple
        run: |
          npm install
          npm run release
          npm run build-report
      - if: steps.maven-cache.outputs.cache-hit != 'true'
        name: Run cd examples/todomvc && lein shadow-release && lein build-report
        working-directory: examples/todomvc
        run: |
          lein shadow-release
          lein build-report
      - if: steps.maven-cache.outputs.cache-hit == 'true'
        run: lein -o ci
      - if: steps.maven-cache.outputs.cache-hit == 'true'
        name: Run cd examples/simple && lein -o shadow-release && lein -o build-report
        working-directory: examples/simple
        run: |
          lein -o shadow-release
          lein -o build-report
      - if: steps.maven-cache.outputs.cache-hit == 'true'
        name: Run cd examples/todomvc && lein -o shadow-release && lein -o build-report
        working-directory: examples/todomvc
        run: |
          lein -o shadow-release
          lein -o build-report
      - uses: actions/upload-artifact@v2
        with:
          name: simple-example-build-report
          path: examples/simple/target/build-report.html
      - uses: actions/upload-artifact@v2
        with:
          name: todomvc-example-build-report
          path: examples/todomvc/target/build-report.html
      - name: Verify cljdoc Configuration
        run: curl -fsSL https://raw.githubusercontent.com/cljdoc/cljdoc/master/script/verify-cljdoc-edn | bash -s doc/cljdoc.edn
      - name: Slack notification
        uses: homoluctus/slatify@v2.0.1
        if: failure() || cancelled()
        with:
          type: ${{ job.status }}
          job_name: re-frame Tests
          channel: '#oss-robots'
          url: ${{ secrets.SLACK_WEBHOOK }}
          commit: true
          token: ${{ secrets.GITHUB_TOKEN }}
