name: ci
on:
  push:
    paths-ignore:
      - "bin/**"
      - "docs/**"
      - "images/**"
      - ".editorconfig"
      - ".gitignore"
      - "CHANGELOG.md"
      - "CITATION.md"
      - "CONTRIBUTING.md"
      - "license.txt"
      - "README.md"

jobs:
  test:
    name: Test
    runs-on: ubuntu-18.04
    container:
      # Source: https://github.com/day8/dockerfile-for-dev-ci-image
      image: day8au/dev-ci:0.0.8
    steps:
      - uses: actions/checkout@v2
      - name: Maven cache
        id: maven-cache
        uses: actions/cache@v1
        with:
          path: /root/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/project.clj') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: npm cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('project.clj') }}-${{ hashFiles('**/deps.cljs') }}
          restore-keys: |
            ${{ runner.os }}-npm-
      - name: shadow-cljs compiler cache
        uses: actions/cache@v2
        with:
          path: .shadow-cljs
          key: ${{ runner.os }}-shadow-cljs-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-shadow-cljs-
      - if: steps.maven-cache.outputs.cache-hit != 'true'
        run: lein karma-once
      - if: steps.maven-cache.outputs.cache-hit != 'true'
        name: Run cd examples/simple && lein shadow compile client
        working-directory: examples/simple
        run: lein shadow compile client
      - if: steps.maven-cache.outputs.cache-hit != 'true'
        name: Run cd examples/todomvc && lein shadow compile client
        working-directory: examples/todomvc
        run: lein shadow compile client
      - if: steps.maven-cache.outputs.cache-hit == 'true'
        run: lein -o karma-once
      - if: steps.maven-cache.outputs.cache-hit == 'true'
        name: Run cd examples/simple && lein -o shadow compile client
        working-directory: examples/simple
        run: lein -o shadow compile client
      - if: steps.maven-cache.outputs.cache-hit == 'true'
        name: Run cd examples/todomvc && lein -o shadow compile client
        working-directory: examples/todomvc
        run: lein -o shadow compile client
      - name: Verify cljdoc Configuration
        run: curl -fsSL https://raw.githubusercontent.com/cljdoc/cljdoc/master/script/verify-cljdoc-edn | bash -s doc/cljdoc.edn
      - name: Slack notification
        uses: homoluctus/slatify@v2.0.1
        if: failure() || cancelled()
        with:
          type: ${{ job.status }}
          job_name: re-frame Tests
          channel: '#oss-robots'
          url: ${{ secrets.SLACK_WEBHOOK }}
          commit: true
          token: ${{ secrets.GITHUB_TOKEN }}
