name: ci
on:
  push:
    paths-ignore:
      - "bin/**"
      - "docs/**"
      - "images/**"
      - ".editorconfig"
      - ".gitignore"
      - "CHANGELOG.md"
      - "CITATION.md"
      - "CONTRIBUTING.md"
      - "license.txt"
      - "README.md"

jobs:
  test:
    name: Test
    runs-on: ubuntu-18.04
    container:
      # Ref: https://github.community/t5/GitHub-Actions/docker-pull-from-public-GitHub-Package-Registry-fail-with-quot/m-p/32782
      image: superstructor/clojure:openjdk-11-lein-2.9.1-node-browser
    steps:
      - uses: actions/checkout@v1
      - run: lein karma-once
      - name: Compile Simple Example
        working-directory: examples/simple
        run: lein shadow compile client
      - name: Compile TodoMVC Example
        working-directory: examples/todomvc
        run: lein shadow compile client
